import { PersonaProfile } from './types';

export const personas: PersonaProfile[] = [
  {
    id: 'ai-builder',
    name: 'AI Builder',
    emoji: '🛠',
    tagline: 'Ship fast, learn faster',
    description: 'You live in the terminal. You want technical depth, real architecture discussions, and people who actually build.',
    topicWeights: { 'AI / Agents / GenAI': 1.0, 'AI infra / devtools / cloud': 0.9, 'Climate / deeptech / hardware': 0.5 },
    formatWeights: { technical_talk_workshop: 1.0, product_demo_showcase: 0.8 },
    scoreWeights: { technical_depth: 1.0, founder_value: 0.6, networking_quality: 0.5 },
  },
  {
    id: 'ai-founder',
    name: 'AI Founder',
    emoji: '🚀',
    tagline: 'Raise, build, repeat',
    description: 'You\'re fundraising, recruiting, or looking for your next co-founder. Every conversation is a potential deal.',
    topicWeights: { 'Founder fundraising / VC': 1.0, 'AI / Agents / GenAI': 0.8, 'GTM / marketing / creator': 0.6 },
    formatWeights: { fundraising_vc: 1.0, community_networking: 0.8 },
    scoreWeights: { founder_value: 1.0, investor_density: 0.9, networking_quality: 0.8 },
  },
  {
    id: 'vc-investor',
    name: 'VC / Investor',
    emoji: '💰',
    tagline: 'Find the signal',
    description: 'You want deal flow, founder density, and the events where the next unicorn founders will be.',
    topicWeights: { 'Founder fundraising / VC': 1.0, 'AI / Agents / GenAI': 0.7, 'Fintech / finance': 0.6 },
    formatWeights: { fundraising_vc: 1.0, community_networking: 0.7 },
    scoreWeights: { investor_density: 1.0, founder_value: 0.8, exclusivity: 0.7 },
  },
  {
    id: 'gtm-marketing',
    name: 'GTM / Marketing',
    emoji: '📣',
    tagline: 'Growth is the product',
    description: 'You want to understand AI-native distribution, meet content creators, and find partnership opportunities.',
    topicWeights: { 'GTM / marketing / creator': 1.0, 'Consumer / creative / media': 0.8, 'AI / Agents / GenAI': 0.5 },
    formatWeights: { community_networking: 0.9, product_demo_showcase: 0.7 },
    scoreWeights: { creator_energy: 1.0, networking_quality: 0.8, hype: 0.6 },
  },
  {
    id: 'creator-media',
    name: 'Creator / Media',
    emoji: '🎬',
    tagline: 'Content is king, distribution is god',
    description: 'You\'re building an audience, creating content, or covering the scene. You want the most interesting stories.',
    topicWeights: { 'Consumer / creative / media': 1.0, 'GTM / marketing / creator': 0.7, 'AI / Agents / GenAI': 0.5 },
    formatWeights: { community_networking: 0.8, other: 0.6 },
    scoreWeights: { creator_energy: 1.0, hype: 0.9, networking_quality: 0.6 },
  },
  {
    id: 'student',
    name: 'Student',
    emoji: '🎓',
    tagline: 'Break into the scene',
    description: 'You want to learn, network, and find your first opportunity in AI. Open events with high learning value.',
    topicWeights: { 'AI / Agents / GenAI': 1.0, 'AI infra / devtools / cloud': 0.7, 'Diversity / women / international': 0.6 },
    formatWeights: { technical_talk_workshop: 1.0, community_networking: 0.8 },
    scoreWeights: { technical_depth: 1.0, networking_quality: 0.7, founder_value: 0.3 },
  },
  {
    id: 'deeptech-robotics',
    name: 'Deeptech / Robotics',
    emoji: '🤖',
    tagline: 'Atoms > bits',
    description: 'You care about hardware, robotics, climate tech, and the physical world. Not another chatbot wrapper.',
    topicWeights: { 'Climate / deeptech / hardware': 1.0, 'AI infra / devtools / cloud': 0.7, 'Health / bio / wellness': 0.5 },
    formatWeights: { technical_talk_workshop: 1.0, product_demo_showcase: 0.9 },
    scoreWeights: { technical_depth: 1.0, founder_value: 0.6, exclusivity: 0.5 },
  },
  {
    id: 'healthcare-ai',
    name: 'Healthcare AI',
    emoji: '🧬',
    tagline: 'AI meets biology',
    description: 'You\'re at the intersection of AI and healthcare, biotech, or wellness. Looking for domain-specific conversations.',
    topicWeights: { 'Health / bio / wellness': 1.0, 'AI / Agents / GenAI': 0.7, 'Climate / deeptech / hardware': 0.4 },
    formatWeights: { technical_talk_workshop: 0.9, community_networking: 0.7 },
    scoreWeights: { technical_depth: 0.9, networking_quality: 0.8, founder_value: 0.6 },
  },
  {
    id: 'international-founder',
    name: 'International Founder',
    emoji: '🌍',
    tagline: 'NYC is the launchpad',
    description: 'You\'re visiting NYC for Tech Week. You want to maximize connections, find US investors, and break into the ecosystem.',
    topicWeights: { 'Diversity / women / international': 1.0, 'Founder fundraising / VC': 0.9, 'AI / Agents / GenAI': 0.6 },
    formatWeights: { community_networking: 1.0, fundraising_vc: 0.8 },
    scoreWeights: { networking_quality: 1.0, investor_density: 0.8, founder_value: 0.7 },
  },
];
